import type { SystemExam, Task } from '../types';

export const SYSTEM_EXAMS: SystemExam[] = [
  {
    id: 'sys-1',
    title: '英语四级考试',
    subtitle: 'CET-4 · 语言类',
    tag: 'CET-4',
    date: '2026-06-13',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '大学英语四级考试，是由国家教育部高等教育司主持的全国性英语考试，主要测试学生的英语综合应用能力，包括听力、阅读、写作和翻译。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-2',
    title: '英语六级考试',
    subtitle: 'CET-6 · 语言类',
    tag: 'CET-6',
    date: '2026-06-13',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '大学英语六级考试，是由国家教育部高等教育司主持的全国性英语考试，难度高于四级，主要测试学生的英语综合应用能力，包括听力、阅读、写作和翻译。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-13',
    title: '高等数学期末考试',
    subtitle: '数学类 · 必修',
    tag: '高数',
    date: '2026-06-20',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '高等数学期末考试，涵盖微积分、极限、级数等核心内容，是理工科学生的重要必修课程。',
    registrationUrl: '',
  },
  {
    id: 'sys-14',
    title: '线性代数期末考',
    subtitle: '数学类 · 必修',
    tag: '线代',
    date: '2026-06-22',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '线性代数期末考试，涵盖矩阵、行列式、向量空间等核心内容。',
    registrationUrl: '',
  },
  {
    id: 'sys-15',
    title: '大学物理期末考',
    subtitle: '物理类 · 必修',
    tag: '物理',
    date: '2026-06-25',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '大学物理期末考试，涵盖力学、热学、电磁学等核心内容。',
    registrationUrl: '',
  },
  {
    id: 'sys-16',
    title: '程序设计基础期末考',
    subtitle: '计算机类 · 必修',
    tag: '程序设计',
    date: '2026-06-28',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '程序设计基础期末考试，涵盖C语言编程、算法基础等核心内容。',
    registrationUrl: '',
  },
  {
    id: 'sys-3',
    title: '计算机二级报名截止',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2026-03-16',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试二级报名截止日期，二级考试主要考查计算机基础知识和使用一种高级计算机语言编写程序以及上机调试的基本技能。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-4',
    title: '计算机二级考试',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2026-05-09',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试二级，主要考查计算机基础知识和使用一种高级计算机语言编写程序以及上机调试的基本技能，包括C语言、Java、Python等多个科目。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-5',
    title: '软考（中级）报名',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-04-11',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试中级报名截止日期，中级考试包括软件设计师、网络工程师、数据库系统工程师等多个专业。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-6',
    title: '软考（中级）考试',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-05-23',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试中级，是由国家人力资源和社会保障部、工业和信息化部领导下的国家级考试，是对计算机与软件专业技术人员职业资格的认定。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-7',
    title: '英语四级报名',
    subtitle: 'CET-4 · 语言类',
    tag: 'CET-4',
    date: '2026-03-25',
    type: 'registration',
    category: 'language',
    isEnabled: true,
    description: '大学英语四级考试报名截止日期，报名成功后请按时参加考试。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-8',
    title: '英语六级报名',
    subtitle: 'CET-6 · 语言类',
    tag: 'CET-6',
    date: '2026-03-25',
    type: 'registration',
    category: 'language',
    isEnabled: true,
    description: '大学英语六级考试报名截止日期，报名成功后请按时参加考试。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-9',
    title: '普通话水平测试',
    subtitle: 'PSC · 语言类',
    tag: '普通话',
    date: '2026-04-18',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '普通话水平测试是对应试人运用普通话的规范程度、熟练程度的口语考试。全部测试内容均以口头方式进行。',
    registrationUrl: 'https://www.cltt.org/',
  },
  {
    id: 'sys-10',
    title: '计算机三级考试',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2026-05-09',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试三级，主要考查计算机网络技术、数据库技术、信息安全技术等领域的专业知识和技能。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-11',
    title: '软考（高级）报名',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-04-11',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试高级报名截止日期，高级考试包括信息系统项目管理师、系统架构设计师等专业。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-12',
    title: '软考（高级）考试',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-05-23',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试高级，是由国家人力资源和社会保障部、工业和信息化部领导下的国家级考试，是对计算机与软件专业技术人员高级职业资格的认定。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'comp-1',
    title: 'ACM-ICPC亚洲区域赛报名',
    subtitle: '国际大学生程序设计竞赛 · 竞赛类',
    tag: 'ACM-ICPC',
    date: '2026-09-15',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: 'ACM-ICPC国际大学生程序设计竞赛亚洲区域赛报名截止日期，这是全球最具影响力的大学生程序设计竞赛之一。',
    registrationUrl: 'https://icpc.global/',
  },
  {
    id: 'comp-2',
    title: 'ACM-ICPC亚洲区域赛',
    subtitle: '国际大学生程序设计竞赛 · 竞赛类',
    tag: 'ACM-ICPC',
    date: '2026-10-18',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: 'ACM-ICPC国际大学生程序设计竞赛亚洲区域赛正式比赛日，来自亚洲各高校的程序设计高手将在赛场上展开激烈角逐，争夺晋级全球总决赛的名额。',
    registrationUrl: 'https://icpc.global/',
  },
  {
    id: 'comp-3',
    title: '蓝桥杯大赛报名截止',
    subtitle: '全国软件和信息技术专业人才大赛 · 竞赛类',
    tag: '蓝桥杯',
    date: '2026-03-20',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '蓝桥杯全国软件和信息技术专业人才大赛是由工业和信息化部人才交流中心主办的全国性IT类学科竞赛，包括软件类、电子类、艺术设计类等多个组别，是计算机专业最具影响力的赛事之一。',
    registrationUrl: 'https://dasai.lanqiao.cn/',
  },
  {
    id: 'comp-4',
    title: '蓝桥杯省赛/国赛',
    subtitle: '全国软件和信息技术专业人才大赛 · 竞赛类',
    tag: '蓝桥杯',
    date: '2026-05-25',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '蓝桥杯全国软件和信息技术专业人才大赛省赛/国赛阶段，参赛选手将在C/C++、Java、Python等语言环境中完成算法设计与编程题目，争夺个人奖项和团队荣誉。',
    registrationUrl: 'https://dasai.lanqiao.cn/',
  },
  {
    id: 'comp-5',
    title: '中国大学生计算机设计大赛报名',
    subtitle: '计算机设计大赛 · 竞赛类',
    tag: '计算机设计大赛',
    date: '2026-03-01',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '中国大学生计算机设计大赛是由教育部大学计算机课程教学指导委员会主办，面向在校大学生的全国性赛事，涵盖软件应用与开发、微课与教学辅助、人工智能等领域。',
    registrationUrl: 'http://jsjdstds.ruc.edu.cn/',
  },
  {
    id: 'comp-6',
    title: '中国大学生计算机设计大赛决赛',
    subtitle: '计算机设计大赛 · 竞赛类',
    tag: '计算机设计大赛',
    date: '2026-07-20',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '中国大学生计算机设计大赛全国总决赛，参赛队伍将通过作品展示和答辩环节，争夺各类别奖项。',
    registrationUrl: 'http://jsjdstds.ruc.edu.cn/',
  },
  {
    id: 'comp-7',
    title: 'CCF CSP认证报名',
    subtitle: '计算机软件能力认证 · 竞赛类',
    tag: 'CCF CSP',
    date: '2026-04-10',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: 'CCF计算机软件能力认证报名截止日期，该认证是中国计算机学会推出的专业技术能力认证，对求职和考研具有重要参考价值。',
    registrationUrl: 'https://cspro.org/',
  },
  {
    id: 'comp-8',
    title: 'CCF CSP认证考试',
    subtitle: '计算机软件能力认证 · 竞赛类',
    tag: 'CCF CSP',
    date: '2026-05-17',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: 'CCF计算机软件能力认证考试，主要考查算法设计和编程能力，采用在线编程方式进行。',
    registrationUrl: 'https://cspro.org/',
  },
  {
    id: 'comp-9',
    title: '全国大学生数学建模竞赛报名',
    subtitle: '数学建模竞赛 · 竞赛类',
    tag: '数学建模',
    date: '2026-05-10',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '全国大学生数学建模竞赛报名截止日期，这是全国高校规模最大的课外科技活动之一，三人组队参赛。',
    registrationUrl: 'https://www.mcm.edu.cn/',
  },
  {
    id: 'comp-10',
    title: '全国大学生数学建模竞赛',
    subtitle: '数学建模竞赛 · 竞赛类',
    tag: '数学建模',
    date: '2026-09-12',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '全国大学生数学建模竞赛正式比赛日，参赛队伍需要在三天内完成模型建立、算法设计和论文撰写。',
    registrationUrl: 'https://www.mcm.edu.cn/',
  },
  {
    id: 'comp-11',
    title: '浙江省大学生程序设计竞赛报名',
    subtitle: '省级竞赛 · 竞赛类',
    tag: '省赛',
    date: '2026-04-25',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '浙江省大学生程序设计竞赛报名截止日期，省内各高校的程序设计精英将在此赛场上一较高下。',
    registrationUrl: 'https://acm.zju.edu.cn/',
  },
  {
    id: 'comp-12',
    title: '浙江省大学生程序设计竞赛',
    subtitle: '省级竞赛 · 竞赛类',
    tag: '省赛',
    date: '2026-05-16',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '浙江省大学生程序设计竞赛正式比赛日，采用ACM赛制，考验选手的算法设计和编程能力。',
    registrationUrl: 'https://acm.zju.edu.cn/',
  },
];

export const ARCHIVED_EXAMS: SystemExam[] = [
  {
    id: 'archived-1',
    title: '已过期-英语四级考试(2025年12月)',
    subtitle: 'CET-4 · 已归档',
    tag: 'CET-4',
    date: '2025-12-14',
    type: 'exam',
    category: 'language',
    isEnabled: false,
    description: '2025年12月英语四级考试，已过期归档。',
    registrationUrl: '',
  },
  {
    id: 'archived-2',
    title: '已过期-计算机二级考试(2025年9月)',
    subtitle: 'NCRE · 已归档',
    tag: 'NCRE',
    date: '2025-09-16',
    type: 'exam',
    category: 'skill',
    isEnabled: false,
    description: '2025年9月全国计算机等级考试二级，已过期归档。',
    registrationUrl: '',
  },
];

export const INITIAL_MANUAL_TASKS: Task[] = [
  {
    id: 'manual-1',
    title: '数据库课程作业提交',
    deadline: '2026-06-02T23:00:00',
    source: 'manual',
    category: 'homework',
    status: 'pending',
    tag: '作业',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-2',
    title: '操作系统实验报告',
    deadline: '2026-06-05T23:59:00',
    source: 'manual',
    category: 'homework',
    status: 'completed',
    tag: '作业',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-3',
    title: '计算机网络考试',
    deadline: '2026-06-02T09:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '考试',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-4',
    title: '软件工程期末考',
    deadline: '2026-06-06T14:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '考试',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-5',
    title: 'CCF CSP认证考试',
    deadline: '2026-06-02T10:00:00',
    source: 'manual',
    category: 'competition',
    status: 'pending',
    tag: 'CCF CSP',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-6',
    title: 'ACM校赛报名',
    deadline: '2026-06-06T18:00:00',
    source: 'manual',
    category: 'registration',
    status: 'pending',
    tag: 'ACM',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-7',
    title: '数据结构期末复习',
    deadline: '2026-06-10T18:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '考试',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-8',
    title: '英语四级模拟考试',
    deadline: '2026-06-12T09:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: 'CET-4',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-9',
    title: '蓝桥杯赛前准备',
    deadline: '2026-06-15T14:00:00',
    source: 'manual',
    category: 'competition',
    status: 'pending',
    tag: '竞赛',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-10',
    title: '软件工程课程设计答辩',
    deadline: '2026-06-18T10:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '答辩',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-11',
    title: '计算机网络作业',
    deadline: '2026-06-20T23:59:00',
    source: 'manual',
    category: 'homework',
    status: 'pending',
    tag: '作业',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-12',
    title: '期末复习计划制定',
    deadline: '2026-06-22T18:00:00',
    source: 'manual',
    category: 'other',
    status: 'completed',
    tag: '计划',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-13',
    title: 'Python编程练习',
    deadline: '2026-06-25T22:00:00',
    source: 'manual',
    category: 'homework',
    status: 'pending',
    tag: '练习',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-14',
    title: '期末考试周开始',
    deadline: '2026-06-28T08:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '考试',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-15',
    title: '高等数学期末考',
    deadline: '2026-07-02T09:00:00',
    source: 'manual',
    category: 'exam',
    status: 'pending',
    tag: '考试',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-16',
    title: '课程论文提交',
    deadline: '2026-07-05T23:59:00',
    source: 'manual',
    category: 'homework',
    status: 'pending',
    tag: '论文',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-17',
    title: '暑期实习申请',
    deadline: '2026-07-10T18:00:00',
    source: 'manual',
    category: 'registration',
    status: 'pending',
    tag: '实习',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-18',
    title: '学期总结报告',
    deadline: '2026-07-15T23:59:00',
    source: 'manual',
    category: 'other',
    status: 'pending',
    tag: '总结',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-19',
    title: '软考报名准备',
    deadline: '2026-07-20T12:00:00',
    source: 'manual',
    category: 'registration',
    status: 'pending',
    tag: '报名',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
];

export function getDaysUntil(dateStr: string): number {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const target = new Date(dateStr);
  target.setHours(0, 0, 0, 0);
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

export function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`;
}

export function formatDateTime(dateStr: string): string {
  const d = new Date(dateStr);
  const hours = d.getHours().toString().padStart(2, '0');
  const mins = d.getMinutes().toString().padStart(2, '0');
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 ${hours}:${mins}`;
}

export function isExpired(dateStr: string): boolean {
  return new Date(dateStr) < new Date();
}

export function isWithinDays(dateStr: string, days: number): boolean {
  const diff = getDaysUntil(dateStr);
  return diff >= 0 && diff <= days;
}