import type { SystemExam, Task } from '../types';

export const SYSTEM_EXAMS: SystemExam[] = [
  {
    id: 'sys-1',
    title: '英语四级考试',
    subtitle: 'CET-4 · 语言类',
    tag: 'CET-4',
    date: '2026-06-13',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '大学英语四级考试，是由国家教育部高等教育司主持的全国性英语考试，主要测试学生的英语综合应用能力，包括听力、阅读、写作和翻译。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-2',
    title: '英语六级考试',
    subtitle: 'CET-6 · 语言类',
    tag: 'CET-6',
    date: '2026-06-13',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '大学英语六级考试，是由国家教育部高等教育司主持的全国性英语考试，难度高于四级，主要测试学生的英语综合应用能力，包括听力、阅读、写作和翻译。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-3',
    title: '计算机二级报名截止',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2026-03-16',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试二级报名截止日期，二级考试主要考查计算机基础知识和使用一种高级计算机语言编写程序以及上机调试的基本技能。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-4',
    title: '计算机二级考试',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2026-05-09',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试二级，主要考查计算机基础知识和使用一种高级计算机语言编写程序以及上机调试的基本技能，包括C语言、Java、Python等多个科目。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-5',
    title: '软考（中级）报名',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-04-11',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试中级报名截止日期，中级考试包括软件设计师、网络工程师、数据库系统工程师等多个专业。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-6',
    title: '软考（中级）考试',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2026-05-23',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试中级，是由国家人力资源和社会保障部、工业和信息化部领导下的国家级考试，是对计算机与软件专业技术人员职业资格的认定。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-7',
    title: '英语四级报名',
    subtitle: 'CET-4 · 语言类',
    tag: 'CET-4',
    date: '2026-03-25',
    type: 'registration',
    category: 'language',
    isEnabled: true,
    description: '大学英语四级考试报名截止日期，四级考试是由国家教育部高等教育司主持的全国性英语考试，主要测试学生的英语综合应用能力。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-8',
    title: '英语六级报名',
    subtitle: 'CET-6 · 语言类',
    tag: 'CET-6',
    date: '2026-03-25',
    type: 'registration',
    category: 'language',
    isEnabled: true,
    description: '大学英语六级考试报名截止日期，六级考试是由国家教育部高等教育司主持的全国性英语考试，难度高于四级，主要测试学生的英语综合应用能力。',
    registrationUrl: 'https://cet.neea.edu.cn/',
  },
  {
    id: 'sys-9',
    title: '计算机三级考试',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE三级',
    date: '2026-05-09',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机等级考试三级，主要考查计算机应用能力，包括网络技术、数据库技术、软件测试技术、信息安全技术、嵌入式系统开发技术等多个方向。',
    registrationUrl: 'https://ncre.neea.edu.cn/',
  },
  {
    id: 'sys-10',
    title: '软考（高级）报名',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考高级',
    date: '2026-04-11',
    type: 'registration',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试高级报名截止日期，高级考试包括信息系统项目管理师、系统分析师、系统架构设计师等多个专业。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-11',
    title: '软考（高级）考试',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考高级',
    date: '2026-05-23',
    type: 'exam',
    category: 'skill',
    isEnabled: true,
    description: '全国计算机技术与软件专业技术资格（水平）考试高级，是由国家人力资源和社会保障部、工业和信息化部领导下的国家级考试，是对计算机与软件专业技术人员职业资格的认定，属于高级职称。',
    registrationUrl: 'https://www.ruankao.org.cn/',
  },
  {
    id: 'sys-12',
    title: '普通话水平测试',
    subtitle: 'PSC · 语言类',
    tag: 'PSC',
    date: '2026-04-18',
    type: 'exam',
    category: 'language',
    isEnabled: true,
    description: '普通话水平测试，是由国家语言文字工作委员会主持的全国性语言考试，主要测试应试人的普通话规范程度、熟练程度和应用能力。',
    registrationUrl: 'https://www.cltt.org/',
  },
  {
    id: 'comp-1',
    title: 'ACM-ICPC亚洲区域赛报名',
    subtitle: '国际大学生程序设计竞赛 · 竞赛类',
    tag: 'ACM-ICPC',
    date: '2026-09-15',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: 'ACM-ICPC国际大学生程序设计竞赛亚洲区域赛，是面向高校在校学生的全球性程序设计竞赛，被誉为计算机软件领域的"奥林匹克"。竞赛涉及算法设计、编程能力和团队协作。',
    registrationUrl: 'https://icpc.global/',
  },
  {
    id: 'comp-2',
    title: 'ACM-ICPC亚洲区域赛',
    subtitle: '国际大学生程序设计竞赛 · 竞赛类',
    tag: 'ACM-ICPC',
    date: '2026-10-18',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: 'ACM-ICPC国际大学生程序设计竞赛亚洲区域赛正式比赛日，来自亚洲各高校的程序设计高手将在赛场上展开激烈角逐，争夺晋级全球总决赛的名额。',
    registrationUrl: 'https://icpc.global/',
  },
  {
    id: 'comp-3',
    title: '蓝桥杯大赛报名截止',
    subtitle: '全国软件和信息技术专业人才大赛 · 竞赛类',
    tag: '蓝桥杯',
    date: '2026-03-20',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '蓝桥杯全国软件和信息技术专业人才大赛是由工业和信息化部人才交流中心主办的全国性IT类学科竞赛，包括软件类、电子类、艺术设计类等多个组别，是计算机专业最具影响力的赛事之一。',
    registrationUrl: 'https://dasai.lanqiao.cn/',
  },
  {
    id: 'comp-4',
    title: '蓝桥杯省赛/国赛',
    subtitle: '全国软件和信息技术专业人才大赛 · 竞赛类',
    tag: '蓝桥杯',
    date: '2026-05-25',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '蓝桥杯全国软件和信息技术专业人才大赛省赛/国赛阶段，参赛选手将在C/C++、Java、Python等语言环境中完成算法设计与编程题目，争夺个人奖项和团队荣誉。',
    registrationUrl: 'https://dasai.lanqiao.cn/',
  },
  {
    id: 'comp-5',
    title: '中国大学生计算机设计大赛报名',
    subtitle: '计算机设计大赛 · 竞赛类',
    tag: '计算机设计大赛',
    date: '2026-03-01',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '中国大学生计算机设计大赛是由教育部大学计算机课程教学指导委员会主办，面向在校大学生的全国性赛事，涵盖软件应用与开发、微课与教学辅助、人工智能等领域。',
    registrationUrl: 'http://jsjdstds.ruc.edu.cn/',
  },
  {
    id: 'comp-6',
    title: '中国大学生计算机设计大赛决赛',
    subtitle: '计算机设计大赛 · 竞赛类',
    tag: '计算机设计大赛',
    date: '2026-07-20',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '中国大学生计算机设计大赛现场决赛阶段，入围团队将进行作品展示和答辩，角逐国家级奖项。',
    registrationUrl: 'http://jsjdstds.ruc.edu.cn/',
  },
  {
    id: 'comp-7',
    title: 'CCF CSP认证报名',
    subtitle: '计算机软件能力认证 · 竞赛类',
    tag: 'CCF CSP',
    date: '2026-04-10',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: 'CCF CSP计算机软件能力认证是由中国计算机学会主办的专业技术能力认证，考查计算机软件从业人员在实际工作中的算法设计和编程能力，是衡量专业水平的重要参考。',
    registrationUrl: 'https://cspro.org/',
  },
  {
    id: 'comp-8',
    title: 'CCF CSP认证考试',
    subtitle: '计算机软件能力认证 · 竞赛类',
    tag: 'CCF CSP',
    date: '2026-05-17',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: 'CCF CSP计算机软件能力认证正式考试，采用在线编程的方式，考查算法设计、数据结构、程序实现等核心能力。',
    registrationUrl: 'https://cspro.org/',
  },
  {
    id: 'comp-9',
    title: '全国大学生数学建模竞赛报名',
    subtitle: '数学建模竞赛 · 竞赛类',
    tag: '数学建模',
    date: '2026-05-10',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '全国大学生数学建模竞赛是由中国工业与应用数学学会主办的全国性赛事，要求参赛队三人一组，在规定时间内完成模型的建立、求解和论文撰写，培养学生运用数学方法和计算机技术解决实际问题的能力。',
    registrationUrl: 'https://www.mcm.edu.cn/',
  },
  {
    id: 'comp-10',
    title: '全国大学生数学建模竞赛',
    subtitle: '数学建模竞赛 · 竞赛类',
    tag: '数学建模',
    date: '2026-09-12',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '全国大学生数学建模竞赛正式比赛，为期三天。参赛队需选择赛题，完成数学模型的建立、算法设计、程序实现和论文写作。',
    registrationUrl: 'https://www.mcm.edu.cn/',
  },
  {
    id: 'comp-11',
    title: '浙江省大学生程序设计竞赛报名',
    subtitle: 'ACM程序设计竞赛 · 竞赛类',
    tag: 'ACM省赛',
    date: '2026-04-25',
    type: 'registration',
    category: 'competition',
    isEnabled: true,
    description: '浙江省大学生程序设计竞赛是由浙江省计算机学会主办的高校程序设计竞赛，采用ACM-ICPC赛制，考查参赛队伍的算法设计、编程能力和团队协作能力。',
    registrationUrl: 'https://www.zjcontest.cn/',
  },
  {
    id: 'comp-12',
    title: '浙江省大学生程序设计竞赛',
    subtitle: 'ACM程序设计竞赛 · 竞赛类',
    tag: 'ACM省赛',
    date: '2026-05-16',
    type: 'competition',
    category: 'competition',
    isEnabled: true,
    description: '浙江省大学生程序设计竞赛正式比赛，各高校程序设计精英同台竞技，争夺团体奖项和个人荣誉。',
    registrationUrl: 'https://www.zjcontest.cn/',
  },
];

export const ARCHIVED_EXAMS: SystemExam[] = [
  {
    id: 'arch-1',
    title: '计算机二级考试（2025年下半年）',
    subtitle: 'NCRE · 技能类',
    tag: 'NCRE',
    date: '2025-11-08',
    type: 'exam',
    category: 'skill',
    isEnabled: false,
  },
  {
    id: 'arch-2',
    title: '英语四级考试（2025年下半年）',
    subtitle: 'CET-4 · 语言类',
    tag: 'CET-4',
    date: '2025-12-13',
    type: 'exam',
    category: 'language',
    isEnabled: false,
  },
  {
    id: 'arch-3',
    title: '软考（中级）考试（2025年下半年）',
    subtitle: '软件水平考试 · 技能类',
    tag: '软考',
    date: '2025-11-08',
    type: 'exam',
    category: 'skill',
    isEnabled: false,
  },
];

export const INITIAL_MANUAL_TASKS: Task[] = [
  {
    id: 'manual-1',
    title: '数据库课程作业提交',
    deadline: '2026-03-18T23:00:00',
    source: 'manual',
    category: 'homework',
    status: 'pending',
    tag: '作业',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'manual-2',
    title: '操作系统实验报告',
    deadline: '2026-03-13T23:59:00',
    source: 'manual',
    category: 'homework',
    status: 'completed',
    tag: '作业',
    isArchived: false,
    createdAt: new Date().toISOString(),
  },
];

export function getDaysUntil(dateStr: string): number {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const target = new Date(dateStr);
  target.setHours(0, 0, 0, 0);
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

export function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`;
}

export function formatDateTime(dateStr: string): string {
  const d = new Date(dateStr);
  const hours = d.getHours().toString().padStart(2, '0');
  const mins = d.getMinutes().toString().padStart(2, '0');
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 ${hours}:${mins}`;
}

export function isExpired(dateStr: string): boolean {
  return new Date(dateStr) < new Date();
}

export function isWithinDays(dateStr: string, days: number): boolean {
  const diff = getDaysUntil(dateStr);
  return diff >= 0 && diff <= days;
}
